<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 40px;
        }
        .header {
            border-bottom: 2px solid #6366f1;
            padding-bottom: 20px;
            margin-bottom: 30px;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
        }
        .invoice-title {
            font-size: 32px;
            font-weight: bold;
            color: #6366f1;
            text-transform: uppercase;
            margin: 0;
        }
        .info-grid {
            width: 100%;
            margin-bottom: 40px;
        }
        .info-col {
            width: 50%;
            vertical-align: top;
        }
        .label {
            font-size: 12px;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 1px;
            display: block;
            margin-bottom: 4px;
        }
        .value {
            font-size: 16px;
            font-weight: 600;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        .table th {
            background-color: #f9fafb;
            text-align: left;
            padding: 12px;
            font-size: 14px;
            color: #374151;
            border-bottom: 1px solid #e5e7eb;
        }
        .table td {
            padding: 12px;
            font-size: 14px;
            border-bottom: 1px solid #e5e7eb;
        }
        .total-section {
            width: 100%;
            text-align: right;
            margin-top: 20px;
        }
        .total-box {
            display: inline-block;
            background-color: #6366f1;
            color: #fff;
            padding: 15px 30px;
            border-radius: 8px;
            font-size: 20px;
            font-weight: bold;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #9ca3af;
        }
        .notes {
            margin-top: 30px;
            padding: 15px;
            background-color: #fefce8;
            border-left: 4px solid #facc15;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="invoice-title">Invoice</h1>
        <div style="text-align: right;">
            <span class="label">Invoice Number</span>
            <span class="value">{{ $invoice->invoice_number }}</span>
        </div>
    </div>

    <table class="info-grid">
        <tr>
            <td class="info-col">
                <span class="label">Billed To:</span>
                <span class="value">{{ $invoice->user->name }}</span><br>
                <span class="value">{{ $invoice->user->email }}</span>
            </td>
            <td class="info-col" style="text-align: right;">
                <span class="label">Issue Date:</span>
                <span class="value">{{ $invoice->invoice_date }}</span>
                <br><br>
                <span class="label">Due Date:</span>
                <span class="value">{{ $invoice->due_date }}</span>
            </td>
        </tr>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th>Description</th>
                <th style="text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Professional Services - Invoice #{{ $invoice->invoice_number }}</td>
                <td style="text-align: right;">${{ number_format($invoice->amount, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="total-section">
        <div class="total-box">
            Total Due: ${{ number_format($invoice->amount, 2) }}
        </div>
    </div>

    @if($invoice->notes)
    <div class="notes">
        <strong>Notes:</strong><br>
        {{ $invoice->notes }}
    </div>
    @endif

    <div class="footer">
        Generated by {{ config('app.name') }} on {{ now()->toFormattedDateString() }}<br>
        Thank you for your business!
    </div>
</body>
</html>
